blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
http_basic_authenticate_with name: "sex", password: "cokgizli", except: [:index, :show]

  def index
    @article = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
    @article = Article.new
  end
  def edit
    @article = Article.find(params[:id])

  end
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end

  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path

  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "sex", password: "cokgizli", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)

  end

  private
  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for :article, url: articles_path do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> aha bu hatalari veriyo bea:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

blog/app/views/articles/edit.html.erb
<h1>Article düzenle bea!</h1>

<%= render 'form' %>

<%= link_to 'Geri dön bea', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Epsini listeliyom bea</h1>

<%= link_to 'Yeni oluştur bea', new_article_path %>

<table>
  <tr>
    <th>Title bea</th>
    <th>Text bea</th>
    <th colspan="2"></th>
  </tr>

  <% @article.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Göster bea', article_path(article) %></td>
    <td><%= link_to 'Düzenle bea', edit_article_path(article) %></td>
    <td><%= link_to 'Sik gitsin bea', article_path(article), method: :delete, data: { confirm: 'Emin misin bea?'} %></td>
  </tr>
  <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>Yeni article oluştur bea!</h1>

<%= render 'form' %>

<%= link_to 'Geri dön bea', articles_path %>

blog/app/views/articles/show.html.erb
<p>
<strong>Title bea:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text bea</strong>
<%= @article.text %>
</p>

<h2>Tükürülen yorumlar bea</h2>
<%= render @article.comments %>

<h2>Yorum tükür bea</h2>
<%= render 'comments/form' %>

<%= link_to 'Düzenle bea', edit_article_path(@article) %>
<%= link_to 'Geri dön bea', articles_path %>

blog/app/views/comments/_comment.html.erb
<p>
  <strong>Tüküren:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Tükürdüğü:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Seek and destroy', [comment.article, comment], method: :delete, data: { confirm: 'sikcen mi bea?'} %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], local:true) do |form| %>
<p>
  <%= form.label :commenter %> <br>
  <%= form.text_field :commenter %>
</p>
<p>
  <%= form.label :body %> <br>
  <%= form.text_area :body %>
</p>
<p>
  <%= form.submit %>
</p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1 style="text-align: center;">Oşgeldin bea!</h1>

<%= link_to 'Bizim bloğa gider bea', controller: 'articles' %>